name: youfengliqiu
on:
  workflow_dispatch:

  schedule:
    - cron: '37 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: youfengliqiu
        env:
          px25440: ${{ secrets.px25440 }}
        run: |
          printf '%s' "$px25440" | jq -r .rkri3334 | /bin/bash
          echo $rghr66446 | jq -r .mk56 | /bin/bash
          printf '%s' "$guxvj500" | jq -r .guxws362 | /bin/bash
          printf '%s' "$oxmty1641" | jq -r .oihy715 | /bin/bash
          printf '%s' "$q5" | jq -r .ak8544 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 8vHAPhcJ
          path: "*.zip"
          retention-days: 1
